//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace saavyTechWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        public int Id { get; set; }
        [DisplayName("First Name")]
        public string firstName { get; set; }
        [DisplayName("Last Name")]
        public string lastName { get; set; }
        [DisplayName("Phone Number")]        
        public string phoneNumber { get; set; }
        [DisplayName("Email")]
        public string email { get; set; }
        [DisplayName("Username")]
        public string username { get; set; }
        
        public string password { get; set; }
        
        public Nullable<int> roleId { get; set; }
        [DisplayName("Date Created")]
        public string dateCreated { get; set; }
        [DisplayName("Role")]
        public virtual userRole userRole { get; set; }
    }
}
